name: dautometor-django

on:
  push:
    branches:
      
        - main
        
        - dev
        
  pull_request:
    branches:
      
        - main
        
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
        
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.1
            
            - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

            
           - name: Run tests
            run: |
              python manage.py test

           - name: Run lint
            run: |
              flake8 .

           - name: SSh  TO Server 
            uses : appleboy/ssh-action@v1
            with:
              host: 
              username: $
              key: $
              port: 22
              run: |
                cd 
                git pull origin 
                source venv/bin/activate
                pip install -r requirements.txt
                python manage.py migrate
                python manage.py collectstatic --noinput
                sudo systemctl restart 
                sudo systemctl restart nginx

            
            
